# 파이썬 버젼 지정
version: "3.12"
services:
  # first container : fastapi
  fastapi:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "alembic revision --autogenerate && \
             alembic upgrade head && \
             uvicorn main:app --host 0.0.0.0 --port 8000"
             
    # db를 위한 환경변수 지정
    environment:
      - DB_HOST=${db}
      - DB_NAME=mp_test
      - DB_USER=meoyong
      - DB_PASS=eodyd456
      - DEBUG=1
    # db라는 컨테이너가 실행되어있어야 이 컨테이너가 실행됨
    depends_on:
      - db

  # second container : PostgreSQL
  db:
    image: postgres:16
    env_file:
      - .env
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fastapi

volumes:
  dev-static-data:
  postgres-data: