"""유저테이블 추가

Revision ID: 4da296f15b7b
Revises: c8fcfef505d9
Create Date: 2024-03-21 10:45:15.066911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da296f15b7b'
down_revision: Union[str, None] = 'c8fcfef505d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('answers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['id'])
    op.drop_column('answers', 'job')
    op.drop_column('answers', 'gender')
    op.drop_column('answers', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('answers', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('answers', sa.Column('job', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
