"""모델수정

Revision ID: c8fcfef505d9
Revises: 9f327551785d
Create Date: 2024-03-19 06:59:52.650777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fcfef505d9'
down_revision: Union[str, None] = '9f327551785d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('answer', sa.Boolean(), nullable=False))
    op.drop_column('answers', 'anwswer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('anwswer', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('answers', 'answer')
    # ### end Alembic commands ###
